---
version: "3.7"
services:
  app:
    command: ["wait-for.sh", "db:5432", "--", "pytest", "/usr/src/test/pytest"]
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - "${PWD}/test/data_files/:/tmp/data_files"
      - "${PWD}/app/:/usr/src/app/"
      - "${PWD}/sql:/usr/src/sql"
      - "${PWD}/scripts:/usr/src/scripts"
      - "${PWD}/test:/usr/src/test"

  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-twodii}"
    image: "postgres:11.5-alpine"
    ports:
      - "${POSTGRES_EXPOSE_PORT:-5432}:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  pgadmin:
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    image: "dpage/pgadmin4"
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - "${PWD}/test/pgadmin4/servers.json:/pgadmin4/servers.json"

volumes:
  pgdata:
