---
name: Python Unit Tests
description: Run python unit tests, using `pytest` inside a docker container
# See /test/pytest/README.md for details on the python unit testing process.
on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build docker image
        run: docker-compose build
      - name: Run unit tests
        run: |
          docker-compose \
          -f docker-compose.yml \
          -f docker-compose.override.yml \
          -f docker-compose.test.yml \
          up \
          --exit-code-from app \
          app
